### ISSUE TITLE
 errorhub { [Error: connect ECONNREFUSED]

### ISSUE THREAD

**Issue by JDiaz11** [maddox/harmony-api#102]
Hi--

I've been running into a problem with the API and hoping someone might be able to offer some assistance. It began when I installed a second hub. I've been successfully running it in Docker on a Synology DiskStation but now when I run it, the hubs are both refusing connections. This error occurs on both hubs:

> errorhub { [Error: connect ECONNREFUSED 192.168.1.XX:5222]	
05:49:07	  code: 'ECONNREFUSED',	
05:49:07	  errno: 'ECONNREFUSED',	
05:49:07	  syscall: 'connect',	
05:49:07	  address: '192.168.1.XX',	
05:49:07	  port: 5222 }

A screenshot of the log is attached.

**What I've tried**:
I've created multiple new containers in an attempt to start fresh, disconnected the new hub and still get the error on the original one which worked correctly prior to this and tried adding the username/password parameters to the config.json file and the environment variables (at separate times), all resulting in the same error.

Please, if anyone can help ... I would really appreciate if someone might shed some light on what's going on and how I may go about correcting this. Thanks so much.

<img width="815" alt="screen shot 2018-12-18 at 1 31 22 am" src="https://user-images.githubusercontent.com/9299272/50136121-b3522100-0264-11e9-91bf-8da572c79534.png">

**Comment by svenove** [comment]
Logitech has pushed a new firmware, blocking all access to the hubs. 

See https://github.com/maddox/harmony-api/issues/101#issuecomment-447817869

**Comment by JDiaz11** [comment]
THANK YOU!!!

**Comment by NeoMatrixJR** [comment]
Aparently there's still a websockets api available on 8088?  I'm interested in seeing how this plays out...if they'll open the old api back up or not.  Either Logitech will need to revert, or I'll have to manually downgrade (see info here: https://www.home-assistant.io/blog/2018/12/17/logitech-harmony-removes-local-api/) or this will need to be updated.... :(

**Comment by maddox** [comment]
Hi everyone. Unfortunately Logitech has decided to close the local API available on the hub.

https://community.logitech.com/s/question/0D55A00008D4bZ4SAJ/harmony-hub-firmware-update-fixes-vulnerabilities

This means you should either downgrade, or find another means to control your media stuff. Home assistant has a patch out to switch to the new found API, if you use Home Assistant, I suggest you switch that from Harmony API.

This effectively ends Harmony API. I'll write a note on the README later today. Thanks for everyone's support!

**Comment by svenove** [comment]
Logitech has changed their mind!
https://community.logitech.com/s/question/0D55A00008D4bZ4SAJ/harmony-hub-firmware-update-fixes-vulnerabilities

Update to beta .210 to restore XMPP and harmony-api should start working again. :)

**Comment by lucasklaassen** [comment]
https://github.com/JordanMartin/harmonyhub-api

This library uses the websocket api and works well!
