### ISSUE TITLE
Logitech reinstates local API

### ISSUE THREAD

**Issue by evandcoleman** [maddox/harmony-api#104]
Logitech has [backtracked on their decision](https://community.logitech.com/s/question/0D55A00008D4bZ4SAJ/harmony-hub-firmware-update-fixes-vulnerabilities) to sunset the API. What does this mean for `harmony-api`? If lack of time is part of the decision, I'd be happy to assist in maintaining it.

**Comment by maddox** [comment]
There’s def opportunity for it to reopen. Let’s see what happens in January when the new-ish api ships.

**Comment by pickmanmike** [comment]
Could you make a note on the readme regarding the possibility? It gives some hope to us committed users :-)

**Comment by maddox** [comment]
Done.
