### ISSUE TITLE
Harmony-api finds Hue lights in Home-Assistant causing duplicates in Alexa

### ISSUE THREAD

**Issue by nkgilley** [maddox/harmony-api#11]
The harmony-api finds every hue light in home assistant which causes Alexa to find both the Hue and HASS instance of my Hue lights. I can go into the Alexa app and 'forget' the HASS instances but the Alexa app will keep automatically finding and adding them back. Any suggestions?

**Comment by nkgilley** [comment]
Whooops too early for me to post issues. This is an issue with Haaska, not harmony-api, sorry.

**Comment by maddox** [comment]
Ha. Just to add to the conversation, you should remove your hue lights from Alexa and just use what shows up from Home Assistant when it bridges everthing over. 

I have the same kind of setup, except a lighting skill I wrote my own. 

Just remember, when using HA, you should just use HA.

**Comment by maddox** [comment]
I guess what I'm trying to say (and didn't in the last comment) is that this isn't really haaska's responsibility. It can't know what you've already added and certainly should t need the ability to white list individual devices. This is up to you and how you organize your set up 

Remove your hue lights from Alexa and all will be well.

**Comment by nkgilley** [comment]
How do you get Alexa to stop finding your Hue lights?

**Comment by maddox** [comment]
I can't say off hand. It's super tricky involving using the hue api directly to delete attached 'apps'. Which is pretty shady in the world of oauth, etc authentication schemes. lol. They need a way to directly delete anything that has permission to talk to your hue hub, and they don't.
