### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by TiiFuchs** [maddox/harmony-api#110]
So should this still work?
I tried it today and I see a log message that the hub was discovered with the correct IP address, but it gets never listed on the http endpoint.

I digged in the app.js and figured, that it gets the ip, but the harmonyhubjs-client's getHarmonyClient() doesn't do its job.

My Harmony hub is on 4.15.264. I read the API was deactivated by Logitech and activated again later... Should it be activated in this version? How can I tell?

**Comment by TiiFuchs** [comment]
Nevermind, you have to enable XMPP in the Harmony Setup section.

![IMG_3611](https://user-images.githubusercontent.com/1958744/84592203-2df10200-ae44-11ea-8525-71c84293e2bc.PNG)

You should add that to the documentation...

**Comment by star114** [comment]
@TiiFuchs 
I had the same problem and thanks to you, I could enable XMPP.

Thank you so much.

**Comment by lucasklaassen** [comment]
I've had good success with this library, it works well!
https://github.com/JordanMartin/harmonyhub-api
