### ISSUE TITLE
multiple harmonyhubjs-discover running

### ISSUE THREAD

**Issue by andrei4002** [maddox/harmony-api#13]
I'm trying to get this thing running, but I'm having an issue with a homebridge plugin I'm using for harmony hub, which is running on the same machine, also uses harmonyhubjs-discover. Basically if i start to run script/server, it gives an error saying that port 5224 is already in use. any (good) idea how to solve this?

**Comment by maddox** [comment]
I assume it's using that port for the UPnP communication so it might not be able to run at the same time. I can look at if it's an option when I use it I guess?

**Comment by maddox** [comment]
From [what I can tell](https://github.com/swissmanu/harmonyhubjs-discover/blob/2a8f1303712c6b6f10eaf49c80f6db7ef21e4336/lib/ping.js#L8) It looks like it's hard coded. This would have to change on the `harmonyhubjs-discover` side. 

If it was configurable, I could use my own port and they could run at the same time.

**Comment by maddox** [comment]
I opened an issue regarding this, it's linked above.

A pull request adding that feature is also a way (and the right/better way for open source :) to get this working.

**Comment by maddox** [comment]
As this is an issue with a dependency, I'm going to close this for now.

**Comment by f00j00** [comment]
Any luck with this?
