### ISSUE TITLE
Issue pulling from Dockerhub

### ISSUE THREAD

**Issue by mehuman** [maddox/harmony-api#23]
Running the supplied docker command gives the error 
``Using default tag: latest
Pulling repository docker.io/jonmaddox/harmony-api
Tag latest not found in repository docker.io/jonmaddox/harmony-api`

I found a repository that has the same Dockerfile at
https://hub.docker.com/r/jawilson/harmony-api/

**Comment by maddox** [comment]
Yeah I don't get why my hook isn't working with Docker Hub. It doesn't seem to be pulling the code and making the Docker.

**Comment by jawilson** [comment]
Looks like you got it linked up!

**Comment by maddox** [comment]
I killed the old thing I made and created a new one that was trigger able. I'm not sure how I messed it up the first time. But I think it's all good now.
