### ISSUE TITLE
Control devices

### ISSUE THREAD

**Issue by NovaGL** [maddox/harmony-api#26]
This looks like a great way to control a harmony hub but does it do devices also?

I currently just use my app to push commands via command line, activity control is easily done but device control has many more functions.

Granted mine is all manual, so I like the auto discovery yours has.

**Comment by maddox** [comment]
> This looks like a great way to control a harmony hub but does it do devices also?

It does not control individual devices at the moment.

> If it only turns on and of activities its a bit useless but still a great start.

I and many other people find it very useful, otherwise it wouldn't exist as it is.

Thanks.

**Comment by rpitera** [comment]
For the record Jon, I find it very useful and wanted to thank you.

**Comment by NovaGL** [comment]
I was too harsh. I apologise. What I meant to say is can you consider doing device support as I have a manual process that does it already so this way won't add any benefit. Thanks for your hard work what you have done is good

**Comment by jawilson** [comment]
@maddox I'm starting to work on adding in the ability to send device commands here: https://github.com/jawilson/harmony-api/tree/device-commands. Expect a PR before too long. Let me know if you have any thoughts on how the topics/values should be structured.

**Comment by maddox** [comment]
Oh awesome. I tried checking out the commands support HarmonyHubJS-Client returned but I only have it 5 mins or so. I was discouraged that they weren't scoped by device as well, but maybe I'm wrong. 

I'd like to be able to return a list of devices and then a list of commands scopes by their devices, via the rest API. This would make it easy to know the slugs to use on the mqtt commands. Which I invison as just being simple namespaced topics with the device, with the command as the message. 

`harmony-api/devices/samsung-tv/command` `power_on`

**Comment by NovaGL** [comment]
This one currently does device control, maybe you can gain something from there. Maybe consider re-opening this issue since it isn't resolved and is still in the pipeline.

https://github.com/bwssytems/restful-harmony

**Comment by maddox** [comment]
## HTTP

The HTTP API should be able to read the device list and their commands. It should also be able to execute the commands.

`GET` `/hubs/:hub_slug/devices` => array of device names (like `/hubs`)
`GET` `/hubs/:hub_slug/devices/:device_slug/commands` => array of command names in slug form
`POST` `/hubs/:hub_slug/devices/:device_slug/activate_command?command=power-on` => trigger command

I sort of hate that command action route but it matches the activities action route: `/hubs/:hub_slug/start_activity?activity=watch-tv`.

`/hubs/:hub_slug/devices/:device_slug/commands/:command_slug` seems nicer to me, but it strays away from the activities action route. Maybe we could change the activity action route to `/hubs/:hub_slug/activities/watch-tv`. We could always keep the old one so it still works for back compat, and deprecate it.

## MQTT

The MQTT API should only be able to execute commands.

`message` `topic`
`harmony-api/hubs/:hub_slug/devices/:device_slug/command` `power-on`

**Comment by NovaGL** [comment]
I prefer this method

`/hubs/:hub_slug/activities/watch-tv`

Then just have one called

`/hubs/:hub_slug/activities/status`

I don't believe you need a status per activity just a global status

**Comment by dale3h** [comment]
Sweet! I'm glad someone finally got around to doing this. I wanted to, but just as the rest of you, I have so much stuff on my plate as it is.

Thanks @jawilson. And thank you @maddox for providing us with an amazingly reliable way to control our Harmony Hub(s)!

**Comment by maddox** [comment]
Thanks!

Lets get this thing merged tonight. I'll be around later.

**Comment by maddox** [comment]
It's official.
