### ISSUE TITLE
Failing Overnight / 5 Second Updates (Docker)

### ISSUE THREAD

**Issue by JIOB** [maddox/harmony-api#29]
Been running this in a Docker on my NAS for a short while to enable control in Home Assistant.

It works great when its running but it seams to stop running overnight every night.

My log has  `Updating state for lounge.` every 5 seconds is this normal? 

Below is the end of my log prior to failing. Any help would be appreciated.

> Updating state for lounge.
> stdout
> 20:55:10
> Hub lost: Lounge at 192.168.0.12.
> stdout
> 20:55:40
> Hub discovered: Lounge at 192.168.0.12.
> stdout
> 20:55:41
> events.js:146
> stderr
> 20:55:41
>       throw err;
> stderr
> 20:55:41
>       ^
> stderr
> 20:55:41
> stderr
> 20:55:41
> Error: Uncaught, unspecified &quot;error&quot; event. (XMPP authentication failure)
> stderr
> 20:55:41
>     at Client.emit (events.js:144:17)
> stderr
> 20:55:41
>     at Client._handleAuthState (/usr/src/app/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/lib/Client.js:295:10)
> stderr
> 20:55:41
>     at Client._handleStanza (/usr/src/app/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/lib/Client.js:233:12)
> stderr
> 20:55:41
>     at Client.onStanza (/usr/src/app/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/lib/Client.js:221:8)
> stderr
> 20:55:41
>     at emitOne (events.js:77:13)
> stderr
> 20:55:41
>     at Connection.emit (events.js:169:7)
> stderr
> 20:55:41
>     at Connection.onStanza (/usr/src/app/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/Connection.js:377:10)
> stderr
> 20:55:41
>     at StreamParser.&lt;anonymous&gt; (/usr/src/app/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/Connection.js:231:10)
> stderr
> 20:55:41
>     at emitOne (events.js:77:13)
> stderr
> 20:55:41
>     at StreamParser.emit (events.js:169:7)
> stderr
> 20:55:41
> stderr
> 20:55:41
> npm info harmony-api@2.0.0 Failed to exec start script
> stderr
> 20:55:41
> npm ERR! Linux 3.10.35
> stderr
> 20:55:41
> npm ERR! argv &quot;/usr/local/bin/node&quot; &quot;/usr/local/bin/npm&quot; &quot;start&quot;
> stderr
> 20:55:41
> npm ERR! node v4.6.0
> stderr
> 20:55:41
> npm ERR! npm  v2.15.9
> stderr
> 20:55:41
> npm ERR! code ELIFECYCLE
> stderr
> 20:55:41
> npm ERR! harmony-api@2.0.0 start: `node app.js`
> stderr
> 20:55:41
> npm ERR! Exit status 1
> stderr
> 20:55:41
> npm ERR! 
> stderr
> 20:55:41
> npm ERR! Failed at the harmony-api@2.0.0 start script 'node app.js'.
> stderr
> 20:55:41
> npm ERR! This is most likely a problem with the harmony-api package,
> stderr
> 20:55:41
> npm ERR! not with npm itself.
> stderr
> 20:55:41
> npm ERR! Tell the author that this fails on your system:
> stderr
> 20:55:41
> npm ERR!     node app.js
> stderr
> 20:55:41
> npm ERR! You can get information on how to open an issue for this project with:
> stderr
> 20:55:41
> npm ERR!     npm bugs harmony-api
> stderr
> 20:55:41
> npm ERR! Or if that isn't available, you can get their info via:
> stderr
> 20:55:41
> npm ERR! 
> stderr
> 20:55:41
> npm ERR!     npm owner ls harmony-api
> stderr
> 20:55:41
> npm ERR! There is likely additional logging output above.
> stderr
> 20:55:41
> stderr
> 20:55:41
> npm ERR! Please include the following file with any support request:
> stderr
> 20:55:41
> npm ERR!     /usr/src/app/npm-debug.log

**Comment by Wutname1** [comment]
I am also having a similar issue below is the output from "docker logs harmony-api"

Hub lost: undefined at undefined.
/usr/src/app/node_modules/parameterize/parameterize.js:98
    var pieces = slug.match(Downcoder.regex);
                     ^

TypeError: Cannot read property 'match' of undefined
    at downcode (/usr/src/app/node_modules/parameterize/parameterize.js:98:22)
    at module.exports (/usr/src/app/node_modules/parameterize/parameterize.js:126:9)
    at Explorer.<anonymous> (/usr/src/app/app.js:66:13)
    at emitOne (events.js:77:13)
    at Explorer.emit (events.js:169:7)
    at /usr/src/app/node_modules/harmonyhubjs-discover/lib/explorer.js:51:9
    at Array.forEach (native)
    at Explorer.executeCleanUp (/usr/src/app/node_modules/harmonyhubjs-discover/lib/explorer.js:44:30)
    at wrapper [as _onTimeout](timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by arraylabs** [comment]
I've been experiencing this issue as well in the latest version (also using docker).

**Comment by JIOB** [comment]
@Wutname1 @arraylabs I managed to overcome this by adding "--restart=always" to my Docker container on first run seams so far to have done the trick hope this helps.
