### ISSUE TITLE
Discovery fails

### ISSUE THREAD

**Issue by tringler** [maddox/harmony-api#36]
Hello,

I'm starting the script with `/harmony-api/script/server` on a RPi3 and it shows:

`Starting Discovery.`

but it never finds my Harmony hub. The hub is up and running and I can control it via [HarmonyHubControl](http://dotnet.work/2016/01/control-your-harmony-hub-with-a-raspberry-pi-linux/)

How can I debug this behaviour? I see no errors at all.

**Comment by maddox** [comment]
Is your RPI3 on a network that supports UPNP and multicast? Are you using this in Docker?

**Comment by tringler** [comment]
Yes, because I'm using [minidlna](https://sourceforge.net/projects/minidlna/) on the same machine in the same network. I also flushed my iptables configuration for testing purposes, but no success. Same behaviour.

No, I'm not using Docker. It is a requirement? I would like to use it as a systemd service like described in https://github.com/maddox/harmony-api/issues/33

**Comment by maddox** [comment]
Yes, multicast upnp discovery won't work if you're not on the same network as the device. You could try pulling the branch on #27 and using that for now. Though you're in a docker container so I'm not sure if you even can.

**Comment by tringler** [comment]
But I am on the same network.

**Comment by maddox** [comment]
Oh good lord, sorry. I basically misread your ENTIRE response. Apologies.

This is definitely weird. You could launch it with:

```
DEBUG=harmonyhubjs:client* npm start
```

to get a more verbose output to see what the discovery client is doing.

**Comment by tringler** [comment]
Don't worry - I'm doing it wrong right?

```
root@elfriede:/usr/local/bin/harmony-api# script/server DEBUG=harmonyhubjs:client* npm start
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
Starting discovery.
```

**Comment by maddox** [comment]
You don't need script/server in there. Just run the command I provided.

**Comment by tringler** [comment]
```

root@elfriede:/usr/local/bin/harmony-api# DEBUG=harmonyhubjs:client* npm start

> harmony-api@2.1.0 start /usr/local/bin/harmony-api
> node app.js

Starting discovery.
```

That's all :(

**Comment by maddox** [comment]
Try re doing all your dependencies:

```
rm -Rf node_modules
npm install
```

What is the ip address of your harmony hub?
What is the ip address of your raspberry pi?

**Comment by tringler** [comment]
Harmony Hub: 192.168.178.111
Raspberry Pi: 192.168.178.200

It reinstalled a lot of packages. Would be to much to paste the whole output here I assume. Now I get:

```
root@elfriede:/usr/local/bin/harmony-api# script/server DEBUG=harmonyhubjs:client* npm start
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
Starting discovery.
'[2016-10-31T18:25:08.863Z] - 192.168.178.103 - GET /hubs_for_index 500 24.563 ms - 32b'
'[2016-10-31T18:25:08.905Z] - 192.168.178.103 - GET /favicon.ico 500 4.238 ms - 32b'
'[2016-10-31T18:25:10.837Z] - 192.168.178.103 - GET /hubs_for_index 500 2.421 ms - 32b'
'[2016-10-31T18:25:10.844Z] - 192.168.178.103 - GET /favicon.ico 500 1.549 ms - 32b'
'[2016-10-31T18:25:11.967Z] - 192.168.178.103 - GET /hubs_for_index 500 0.990 ms - 32b'
'[2016-10-31T18:25:11.970Z] - 192.168.178.103 - GET /favicon.ico 500 1.123 ms - 32b'
'[2016-10-31T18:25:12.649Z] - 192.168.178.103 - GET /hubs_for_index 500 0.830 ms - 32b'
'[2016-10-31T18:25:12.652Z] - 192.168.178.103 - GET /favicon.ico 500 1.254 ms - 32b'
error: restarting script because change changed
error: Forever detected script was killed by signal: SIGKILL
error: Script restart attempt #1
Starting discovery.
'[2016-10-31T18:26:01.287Z] - 192.168.178.103 - GET /hubs_for_index 500 20.379 ms - 32b'
'[2016-10-31T18:26:01.357Z] - 192.168.178.103 - GET /favicon.ico 500 3.329 ms - 32b'
'[2016-10-31T18:26:05.651Z] - 192.168.178.103 - GET /hubs 500 2.283 ms - 32b'
'[2016-10-31T18:26:05.814Z] - 192.168.178.103 - GET /favicon.ico 500 1.812 ms - 32b'
'[2016-10-31T18:26:07.348Z] - 192.168.178.103 - GET /favicon.ico 500 0.976 ms - 32b'
'[2016-10-31T18:26:08.311Z] - 192.168.178.103 - GET /hubs_for_index 500 1.545 ms - 32b'
'[2016-10-31T18:26:08.368Z] - 192.168.178.103 - GET /favicon.ico 500 1.404 ms - 32b'
'[2016-10-31T18:29:15.908Z] - 192.168.178.103 - GET /hubs_for_index 500 1.366 ms - 32b'
'[2016-10-31T18:29:15.913Z] - 192.168.178.103 - GET /favicon.ico 500 1.586 ms - 32b'
'[2016-10-31T18:29:17.320Z] - 192.168.178.103 - GET /hubs_for_index 500 1.349 ms - 32b'
'[2016-10-31T18:29:17.325Z] - 192.168.178.103 - GET /favicon.ico 500 1.426 ms - 32b'
'[2016-10-31T18:29:18.157Z] - 192.168.178.103 - GET /hubs_for_index 500 1.145 ms - 32b'
'[2016-10-31T18:29:18.162Z] - 192.168.178.103 - GET /favicon.ico 500 1.445 ms - 32b'
```

**Comment by maddox** [comment]
Don't use `script/server`

That actually calls `npm start`. For debug just manually start it with:

```
script/server DEBUG=harmonyhubjs:client* npm start
```

Either way it still isn't finding your hub. I don't get it.

/cc @jawilson Got any idea about this?

**Comment by tringler** [comment]
Sorry. Will keep that in my mind, but you wanted to say start it with: `DEBUG=harmonyhubjs:client* npm start` instead of `script/server DEBUG=harmonyhubjs:client* npm start` right?

**Comment by maddox** [comment]
yes [script/server](https://github.com/maddox/harmony-api/blob/master/script/server) just calls the start on it's own.

**Comment by tringler** [comment]
Sorry! I flushed iptables and it works now.
