### ISSUE TITLE
Improve config to bypass discovery

### ISSUE THREAD

**Issue by pogil** [maddox/harmony-api#39]
I'm having trouble with the auto-discovery in harmonyhubjs-discover in my setup and rather than fight it I thought it might be convenient to improve the config to support user specified hubs. I read through issue #36 and wasn't able to reproduce the iptable flushing, and I'm not sure that's the underlying root cause in my case - I'm running this on "Ubuntu on Windows" support in Windows 10 Anniversary Update.  I know the IP of my hub and was able to make a local edit to hardcode my hub, but figured it might be nice to generalize this and contribute it back in case other users have difficulties with the discovery tool.

My thought is that I could extend config.json checking to support a list of hub-slug/ip pairs. Here are some things I could use input on:

1. Verbose or compact syntax in the config. I could use a compact map of slug to IP:
```
harmony_hubs : {
  "living-room" : "192.168.1.3", 
  "bedroom" : "192.168.1.4",
}
``` 
which reads nicely once filled in, but isn't clearly documented. Or as
```
harmony_hubs : [
  { 
    "slug" : "living-room", 
    "ip" : "192.168.1.3" 
  }, 
  { 
    "slug" : "bedroom", 
    "ip" : "192.168.1.4" 
  },
]
```
which is less compact but more explicit.

2. If hubs are specified, should discovery be enabled, disabled, or an option in the config? If an option, do you have a recommended parameter name?

3. Are there any tests I would need to add?

**Comment by maddox** [comment]
This [was implemented](https://github.com/maddox/harmony-api/pull/27) but has yet to be merged. Could you try that branch, see how it works for you, and report back?

Thanks!

**Comment by pogil** [comment]
@maddox it works well for me and merges cleanly with master. I'll leave a comment on #27 too.

**Comment by pogil** [comment]
Duplicate of #27
