### ISSUE TITLE
automation devices?

### ISSUE THREAD

**Issue by sinedied** [maddox/harmony-api#41]
Thanks for your great project, I love it :)

I'm just missing a nice thing, that would be to automate home automation device attached to my harmony hub, for example my philips hue and scenes (ok bad example as hue lights already have an api, but I would only needs the commands available from my harmony hub).

Would it be possible?

**Comment by maddox** [comment]
This is not possible currently.

Check out something like [Home Assistant](https://home-assistant.io). You can add your hue lights and your harmony hub via this project all in a single place. Then you have a central location to control and automate all your devices.
