### ISSUE TITLE
How Do You Get Discovery Working In Docker?

### ISSUE THREAD

**Issue by CWSpear** [maddox/harmony-api#62]
Trying to use the Docker version. Works fine outside of Docker, but it won't discover the hubs. Tried mapping extra ports (`docker-compose` config), but it won't ever find the hubs.

```yaml
ports:
  - 61991:61991
  - 61991:61991\udp
  - 5224:5224
  - 5224:5224\udp
```

**Comment by CWSpear** [comment]
I had to add `network_mode: host` (the equivalent of `--net=host` on the CLI).

It only worked on Linux... on my Mac (using Docker for Mac), I'd probably have to configure some stuff with the VM.

May be worth adding these notes to the docs?

**Edit:** Looks like adding all the ports was unnecessary, too.

Also... oh my gosh, just realized you _did_ have a note about `--net=host`. The last wasted 3 hours is all on me, lol

**Comment by NeoMatrixJR** [comment]
What made you add the ports listed above and did you keep them after adding host?  I have my docker set for host but it still won't find my hub.
