### ISSUE TITLE
Stuck on "Starting Discovery" in development mod

### ISSUE THREAD

**Issue by camcdonald1** [maddox/harmony-api#80]
I've installed on a full Ubuntu 16.04 distro (not docker). I can't install the production server so am attempting to run the script/server in development mode. In dev mode the script runs but never finds the Hub on my home network. I ran debug and get the message below. I've tried flushing IPtables but that doesn't help. The hub is working and discovered on my home network, just not through Harmony-API. Note, I'm not looking for MQTT functionality yet, just HTTP to begin with. Let me know if there are known issues or if you have ideas on how I can debug this problem and get the HTTP server working.

>>harmony-api@2.3.5 start /home/chris/harmony-api-master
node app.js
Starting Discovery.
>

**Comment by maddox** [comment]
Is upnp disabled on your router? It uses UPNP to discover the hub. Also, make sure both the server and hubs are on the same subnet.

**Comment by camcdonald1** [comment]
Thanks for the fast reply. UPNP was initially on. I turned it off, restarted and then flipped it back to on. Still no resolution. I'm not sure about the subnet question, or how to verify that - but that is what I will google next.

**Comment by camcdonald1** [comment]
I've confirmed both the server and hub are on the same subnet. Also, as previously stated UPNP is enabled.

**Comment by camcdonald1** [comment]
This has been resolved after adding eth0 to my etc startup config file and connecting an ethernet cord to hardwire connect my laptop.
