### ISSUE TITLE
Recurring Syntax Error (unexpected token)?

### ISSUE THREAD

**Issue by stevetb77** [maddox/harmony-api#82]
Thanks so much for this software, I'm very thrilled this exists!

Many of my POST requests are failing as the hub is lost, devices are lost , device commands are lost.  This is because of a recurring crash where the script is restarting over and over again.  Sometimes the error happens so frequently that it's down more than it is up.  Appears to be the same error each time.  I have no idea what to do.  Please advise, thank you!

The error is: "SyntaxError: Unexpected token ] in JSON at position 73682"

Here is what the output looks like..
"warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
Starting discovery.
Hub discovered: Great Room at 192.168.0.11.
Updating activities for great-room.
Updating state for great-room.
Updating devices for great-room.
Updating state for great-room.
Updating state for great-room.
Updating state for great-room.
Updating state for great-room.
Updating state for great-room.
Updating state for great-room.
Updating state for great-room.
Updating state for great-room.
Updating state for great-room.
Updating state for great-room.
Updating state for great-room.
Updating activities for great-room.
Updating devices for great-room.
Updating state for great-room.
undefined:1
{"activity":[{"rules":[],"label":"Lower Screen","isTuningDefault":false,"activityTypeDisplayName":"Default","enterActions":[{"name":"SendCommand","parameters":{"Command":"directiondown","DeviceId":"49203209","Modifier":"press"}}],"fixit":{"49203207":{"id":"49203207","isRelativePower":true,"Power":"Off"},"49203209":{"id":"49203209","isAlwaysOn":"true","Power":"On"},"49203208":{"id":"49203208","Power":"Off"},"49920389":{"id":"49920389","isManualPower":true},"49920888":{"id":"49920888","Power":"Off"}},"baseImageUri":"https:\/\/rcbu-test-ssl-amr.s3.amazonaws.com\/","zones":null,"type":"VirtualGeneric","isAVActivity":true,"id":"30232500","controlGroup":[{"name":"NavigationBasic","function":[{"action":"{\"command\":\"DirectionDown\",\"type\":\"IRCommand\",\"deviceId\":\"49203209\"}","name":"DirectionDown","label":"Direction Down"},{"action":"{\"command\":\"DirectionUp\",\"type\":\"IRCommand\",\"deviceId\":\"49203209\"}","name":"DirectionUp","label":"Direction Up"},{"action":"{\"command\":\"OK\",\"type

SyntaxError: Unexpected token ] in JSON at position 73682
    at JSON.parse (<anonymous>)
    at /home/harmony-api/harmony-api/node_modules/harmonyhubjs-client/lib/harmonyclient.js:39:34
    at Array.forEach (native)
    at HarmonyClient.handleStanza (/home/harmony-api/harmony-api/node_modules/harmonyhubjs-client/lib/harmonyclient.js:31:32)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:189:7)
    at Client._handleStanza (/home/harmony-api/harmony-api/node_modules/node-xmpp-client/lib/Client.js:228:12)
    at Client.onStanza (/home/harmony-api/harmony-api/node_modules/node-xmpp-client/lib/Client.js:222:8)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:189:7)
error: Forever detected script exited with code: 1
error: Script restart attempt #1
Starting discovery.
Hub discovered: Great Room at 192.168.0.11.
Updating activities for great-room.
Updating state for great-room.
Updating devices for great-room.
undefined:1
{"activity":[{"rules":[],"label":"Lower Screen","isTuningDefault":false,"activityTypeDisplayName":"Default","enterActions":[{"name":"SendCommand","parameters":{"Command":"directiondown","DeviceId":"49203209","Modifier":"press"}}],"fixit":{"49203207":{"id":"49203207","isRelativePower":true,"Power":"Off"},"49203209":{"id":"49203209","isAlwaysOn":"true","Power":"On"},"49203208":{"id":"49203208","Power":"Off"},"49920389":{"id":"49920389","isManualPower":true},"49920888":{"id":"49920888","Power":"Off"}},"baseImageUri":"https:\/\/rcbu-test-ssl-amr.s3.amazonaws.com\/","zones":null,"type":"VirtualGeneric","isAVActivity":true,"id":"30232500","controlGroup":[{"name":"NavigationBasic","function":[{"action":"{\"command\":\"DirectionDown\",\"type\":\"IRCommand\",\"deviceId\":\"49203209\"}","name":"DirectionDown","label":"Direction Down"},{"action":"{\"command\":\"DirectionUp\",\"type\":\"IRCommand\",\"deviceId\":\"49203209\"}","name":"DirectionUp","label":"Direction Up"},{"action":"{\"command\":\"OK\",\"type

SyntaxError: Unexpected token ] in JSON at position 73682
    at JSON.parse (<anonymous>)
    at /home/harmony-api/harmony-api/node_modules/harmonyhubjs-client/lib/harmonyclient.js:39:34
    at Array.forEach (native)
    at HarmonyClient.handleStanza (/home/harmony-api/harmony-api/node_modules/harmonyhubjs-client/lib/harmonyclient.js:31:32)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:189:7)
    at Client._handleStanza (/home/harmony-api/harmony-api/node_modules/node-xmpp-client/lib/Client.js:228:12)
    at Client.onStanza (/home/harmony-api/harmony-api/node_modules/node-xmpp-client/lib/Client.js:222:8)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:189:7)
error: Forever detected script exited with code: 1
error: Script restart attempt #2
Starting discovery.
Hub discovered: Great Room at 192.168.0.11.
Updating activities for great-room.
Updating state for great-room.
Updating devices for great-room.
Updating state for great-room.
undefined:1
{"activity":[{"rules":[],"label":"Lower Screen","isTuningDefault":false,"activityTypeDisplayName":"Default","enterActions":[{"name":"SendCommand","parameters":{"Command":"directiondown","DeviceId":"49203209","Modifier":"press"}}],"fixit":{"49203207":{"id":"49203207","isRelativePower":true,"Power":"Off"},"49203209":{"id":"49203209","isAlwaysOn":"true","Power":"On"},"49203208":{"id":"49203208","Power":"Off"},"49920389":{"id":"49920389","isManualPower":true},"49920888":{"id":"49920888","Power":"Off"}},"baseImageUri":"https:\/\/rcbu-test-ssl-amr.s3.amazonaws.com\/","zones":null,"type":"VirtualGeneric","isAVActivity":true,"id":"30232500","controlGroup":[{"name":"NavigationBasic","function":[{"action":"{\"command\":\"DirectionDown\",\"type\":\"IRCommand\",\"deviceId\":\"49203209\"}","name":"DirectionDown","label":"Direction Down"},{"action":"{\"command\":\"DirectionUp\",\"type\":\"IRCommand\",\"deviceId\":\"49203209\"}","name":"DirectionUp","label":"Direction Up"},{"action":"{\"command\":\"OK\",\"type

SyntaxError: Unexpected token ] in JSON at position 73682
    at JSON.parse (<anonymous>)
    at /home/harmony-api/harmony-api/node_modules/harmonyhubjs-client/lib/harmonyclient.js:39:34
    at Array.forEach (native)
    at HarmonyClient.handleStanza (/home/harmony-api/harmony-api/node_modules/harmonyhubjs-client/lib/harmonyclient.js:31:32)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:189:7)
    at Client._handleStanza (/home/harmony-api/harmony-api/node_modules/node-xmpp-client/lib/Client.js:228:12)
    at Client.onStanza (/home/harmony-api/harmony-api/node_modules/node-xmpp-client/lib/Client.js:222:8)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:189:7)
error: Forever detected script exited with code: 1
error: Script restart attempt #3
Starting discovery.
Hub discovered: Great Room at 192.168.0.11.
Updating activities for great-room.
Updating state for great-room.
Updating devices for great-room.
undefined:1
{"activity":[{"rules":[],"label":"Lower Screen","isTuningDefault":false,"activityTypeDisplayName":"Default","enterActions":[{"name":"SendCommand","parameters":{"Command":"directiondown","DeviceId":"49203209","Modifier":"press"}}],"fixit":{"49203207":{"id":"49203207","isRelativePower":true,"Power":"Off"},"49203209":{"id":"49203209","isAlwaysOn":"true","Power":"On"},"49203208":{"id":"49203208","Power":"Off"},"49920389":{"id":"49920389","isManualPower":true},"49920888":{"id":"49920888","Power":"Off"}},"baseImageUri":"https:\/\/rcbu-test-ssl-amr.s3.amazonaws.com\/","zones":null,"type":"VirtualGeneric","isAVActivity":true,"id":"30232500","controlGroup":[{"name":"NavigationBasic","function":[{"action":"{\"command\":\"DirectionDown\",\"type\":\"IRCommand\",\"deviceId\":\"49203209\"}","name":"DirectionDown","label":"Direction Down"},{"action":"{\"command\":\"DirectionUp\",\"type\":\"IRCommand\",\"deviceId\":\"49203209\"}","name":"DirectionUp","label":"Direction Up"},{"action":"{\"command\":\"OK\",\"type

SyntaxError: Unexpected token ] in JSON at position 73682
    at JSON.parse (<anonymous>)
    at /home/harmony-api/harmony-api/node_modules/harmonyhubjs-client/lib/harmonyclient.js:39:34
    at Array.forEach (native)
    at HarmonyClient.handleStanza (/home/harmony-api/harmony-api/node_modules/harmonyhubjs-client/lib/harmonyclient.js:31:32)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:189:7)
    at Client._handleStanza (/home/harmony-api/harmony-api/node_modules/node-xmpp-client/lib/Client.js:228:12)
    at Client.onStanza (/home/harmony-api/harmony-api/node_modules/node-xmpp-client/lib/Client.js:222:8)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:189:7)
error: Forever detected script exited with code: 1
error: Script restart attempt #4
Starting discovery.
Hub discovered: Great Room at 192.168.0.11.
Updating activities for great-room.
Updating state for great-room.
Updating devices for great-room.
Updating state for great-room.
undefined:1
{"activity":[{"rules":[],"label":"Lower Screen","isTuningDefault":false,"activityTypeDisplayName":"Default","enterActions":[{"name":"SendCommand","parameters":{"Command":"directiondown","DeviceId":"49203209","Modifier":"press"}}],"fixit":{"49203207":{"id":"49203207","isRelativePower":true,"Power":"Off"},"49203209":{"id":"49203209","isAlwaysOn":"true","Power":"On"},"49203208":{"id":"49203208","Power":"Off"},"49920389":{"id":"49920389","isManualPower":true},"49920888":{"id":"49920888","Power":"Off"}},"baseImageUri":"https:\/\/rcbu-test-ssl-amr.s3.amazonaws.com\/","zones":null,"type":"VirtualGeneric","isAVActivity":true,"id":"30232500","controlGroup":[{"name":"NavigationBasic","function":[{"action":"{\"command\":\"DirectionDown\",\"type\":\"IRCommand\",\"deviceId\":\"49203209\"}","name":"DirectionDown","label":"Direction Down"},{"action":"{\"command\":\"DirectionUp\",\"type\":\"IRCommand\",\"deviceId\":\"49203209\"}","name":"DirectionUp","label":"Direction Up"},{"action":"{\"command\":\"OK\",\"type

SyntaxError: Unexpected token ] in JSON at position 73682
    at JSON.parse (<anonymous>)
    at /home/harmony-api/harmony-api/node_modules/harmonyhubjs-client/lib/harmonyclient.js:39:34
    at Array.forEach (native)
    at HarmonyClient.handleStanza (/home/harmony-api/harmony-api/node_modules/harmonyhubjs-client/lib/harmonyclient.js:31:32)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:189:7)
    at Client._handleStanza (/home/harmony-api/harmony-api/node_modules/node-xmpp-client/lib/Client.js:228:12)
    at Client.onStanza (/home/harmony-api/harmony-api/node_modules/node-xmpp-client/lib/Client.js:222:8)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:189:7)
error: Forever detected script exited with code: 1
error: Script restart attempt #5
Starting discovery.
Hub discovered: Great Room at 192.168.0.11.
Updating activities for great-room.
Updating state for great-room.
Updating devices for great-room.
Updating state for great-room.
undefined:1
{"activity":[{"rules":[],"label":"Lower Screen","isTuningDefault":false,"activityTypeDisplayName":"Default","enterActions":[{"name":"SendCommand","parameters":{"Command":"directiondown","DeviceId":"49203209","Modifier":"press"}}],"fixit":{"49203207":{"id":"49203207","isRelativePower":true,"Power":"Off"},"49203209":{"id":"49203209","isAlwaysOn":"true","Power":"On"},"49203208":{"id":"49203208","Power":"Off"},"49920389":{"id":"49920389","isManualPower":true},"49920888":{"id":"49920888","Power":"Off"}},"baseImageUri":"https:\/\/rcbu-test-ssl-amr.s3.amazonaws.com\/","zones":null,"type":"VirtualGeneric","isAVActivity":true,"id":"30232500","controlGroup":[{"name":"NavigationBasic","function":[{"action":"{\"command\":\"DirectionDown\",\"type\":\"IRCommand\",\"deviceId\":\"49203209\"}","name":"DirectionDown","label":"Direction Down"},{"action":"{\"command\":\"DirectionUp\",\"type\":\"IRCommand\",\"deviceId\":\"49203209\"}","name":"DirectionUp","label":"Direction Up"},{"action":"{\"command\":\"OK\",\"type

SyntaxError: Unexpected token ] in JSON at position 73682
    at JSON.parse (<anonymous>)
    at /home/harmony-api/harmony-api/node_modules/harmonyhubjs-client/lib/harmonyclient.js:39:34
    at Array.forEach (native)
    at HarmonyClient.handleStanza (/home/harmony-api/harmony-api/node_modules/harmonyhubjs-client/lib/harmonyclient.js:31:32)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:189:7)
    at Client._handleStanza (/home/harmony-api/harmony-api/node_modules/node-xmpp-client/lib/Client.js:228:12)
    at Client.onStanza (/home/harmony-api/harmony-api/node_modules/node-xmpp-client/lib/Client.js:222:8)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:189:7)
error: Forever detected script exited with code: 1
error: Script restart attempt #6
Starting discovery.
Hub discovered: Great Room at 192.168.0.11.
Updating activities for great-room.
Updating state for great-room.
Updating devices for great-room.
Updating state for great-room.
undefined:1
{"activity":[{"rules":[],"label":"Lower Screen","isTuningDefault":false,"activityTypeDisplayName":"Default","enterActions":[{"name":"SendCommand","parameters":{"Command":"directiondown","DeviceId":"49203209","Modifier":"press"}}],"fixit":{"49203207":{"id":"49203207","isRelativePower":true,"Power":"Off"},"49203209":{"id":"49203209","isAlwaysOn":"true","Power":"On"},"49203208":{"id":"49203208","Power":"Off"},"49920389":{"id":"49920389","isManualPower":true},"49920888":{"id":"49920888","Power":"Off"}},"baseImageUri":"https:\/\/rcbu-test-ssl-amr.s3.amazonaws.com\/","zones":null,"type":"VirtualGeneric","isAVActivity":true,"id":"30232500","controlGroup":[{"name":"NavigationBasic","function":[{"action":"{\"command\":\"DirectionDown\",\"type\":\"IRCommand\",\"deviceId\":\"49203209\"}","name":"DirectionDown","label":"Direction Down"},{"action":"{\"command\":\"DirectionUp\",\"type\":\"IRCommand\",\"deviceId\":\"49203209\"}","name":"DirectionUp","label":"Direction Up"},{"action":"{\"command\":\"OK\",\"type

SyntaxError: Unexpected token ] in JSON at position 73682
    at JSON.parse (<anonymous>)
    at /home/harmony-api/harmony-api/node_modules/harmonyhubjs-client/lib/harmonyclient.js:39:34
    at Array.forEach (native)
    at HarmonyClient.handleStanza (/home/harmony-api/harmony-api/node_modules/harmonyhubjs-client/lib/harmonyclient.js:31:32)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:189:7)
    at Client._handleStanza (/home/harmony-api/harmony-api/node_modules/node-xmpp-client/lib/Client.js:228:12)
    at Client.onStanza (/home/harmony-api/harmony-api/node_modules/node-xmpp-client/lib/Client.js:222:8)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:189:7)
error: Forever detected script exited with code: 1
error: Script restart attempt #7
Starting discovery.
Hub discovered: Great Room at 192.168.0.11.
Updating activities for great-room.
Updating state for great-room.
Updating devices for great-room.
Updating state for great-room.
Updating state for great-room.
Updating state for great-room.
Updating state for great-room.
Updating state for great-room.
Updating state for great-room.
Updating state for great-room.
Updating state for great-room.
Updating state for great-room.
Updating state for great-room.
Updating state for great-room.
Updating activities for great-room.
Updating devices for great-room.
Updating state for great-room.
Updating state for great-room.
Updating state for great-room.
Updating state for great-room.
Updating state for great-room.
Updating state for great-room.
Updating state for great-room.
Updating state for great-room.
Updating state for great-room.
Updating state for great-room.
Updating state for great-room.
Updating state for great-room.
Updating activities for great-room.
Updating devices for great-room.
Updating state for great-room.
Updating state for great-room.
Hub lost: Great Room at 192.168.0.11.
Hub discovered: Great Room at 192.168.0.11.
undefined:1
{"activity":[{"rules":[],"label":"Lower Screen","isTuningDefault":false,"activityTypeDisplayName":"Default","enterActions":[{"name":"SendCommand","parameters":{"Command":"directiondown","DeviceId":"49203209","Modifier":"press"}}],"fixit":{"49203207":{"id":"49203207","isRelativePower":true,"Power":"Off"},"49203209":{"id":"49203209","isAlwaysOn":"true","Power":"On"},"49203208":{"id":"49203208","Power":"Off"},"49920389":{"id":"49920389","isManualPower":true},"49920888":{"id":"49920888","Power":"Off"}},"baseImageUri":"https:\/\/rcbu-test-ssl-amr.s3.amazonaws.com\/","zones":null,"type":"VirtualGeneric","isAVActivity":true,"id":"30232500","controlGroup":[{"name":"NavigationBasic","function":[{"action":"{\"command\":\"DirectionDown\",\"type\":\"IRCommand\",\"deviceId\":\"49203209\"}","name":"DirectionDown","label":"Direction Down"},{"action":"{\"command\":\"DirectionUp\",\"type\":\"IRCommand\",\"deviceId\":\"49203209\"}","name":"DirectionUp","label":"Direction Up"},{"action":"{\"command\":\"OK\",\"type

SyntaxError: Unexpected token ] in JSON at position 73682
    at JSON.parse (<anonymous>)
    at /home/harmony-api/harmony-api/node_modules/harmonyhubjs-client/lib/harmonyclient.js:39:34
    at Array.forEach (native)
    at HarmonyClient.handleStanza (/home/harmony-api/harmony-api/node_modules/harmonyhubjs-client/lib/harmonyclient.js:31:32)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:189:7)
    at Client._handleStanza (/home/harmony-api/harmony-api/node_modules/node-xmpp-client/lib/Client.js:228:12)
    at Client.onStanza (/home/harmony-api/harmony-api/node_modules/node-xmpp-client/lib/Client.js:222:8)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:189:7)
error: Forever detected script exited with code: 1
error: Script restart attempt #8
Starting discovery.
Hub discovered: Great Room at 192.168.0.11.
Updating activities for great-room.
Updating state for great-room.
Updating devices for great-room.
Updating state for great-room.
Updating state for great-room.
Updating state for great-room.
undefined:1
{"activity":[{"rules":[],"label":"Lower Screen","isTuningDefault":false,"activityTypeDisplayName":"Default","enterActions":[{"name":"SendCommand","parameters":{"Command":"directiondown","DeviceId":"49203209","Modifier":"press"}}],"fixit":{"49203207":{"id":"49203207","isRelativePower":true,"Power":"Off"},"49203209":{"id":"49203209","isAlwaysOn":"true","Power":"On"},"49203208":{"id":"49203208","Power":"Off"},"49920389":{"id":"49920389","isManualPower":true},"49920888":{"id":"49920888","Power":"Off"}},"baseImageUri":"https:\/\/rcbu-test-ssl-amr.s3.amazonaws.com\/","zones":null,"type":"VirtualGeneric","isAVActivity":true,"id":"30232500","controlGroup":[{"name":"NavigationBasic","function":[{"action":"{\"command\":\"DirectionDown\",\"type\":\"IRCommand\",\"deviceId\":\"49203209\"}","name":"DirectionDown","label":"Direction Down"},{"action":"{\"command\":\"DirectionUp\",\"type\":\"IRCommand\",\"deviceId\":\"49203209\"}","name":"DirectionUp","label":"Direction Up"},{"action":"{\"command\":\"OK\",\"type

SyntaxError: Unexpected token ] in JSON at position 73682
    at JSON.parse (<anonymous>)
    at /home/harmony-api/harmony-api/node_modules/harmonyhubjs-client/lib/harmonyclient.js:39:34
    at Array.forEach (native)
    at HarmonyClient.handleStanza (/home/harmony-api/harmony-api/node_modules/harmonyhubjs-client/lib/harmonyclient.js:31:32)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:189:7)
    at Client._handleStanza (/home/harmony-api/harmony-api/node_modules/node-xmpp-client/lib/Client.js:228:12)
    at Client.onStanza (/home/harmony-api/harmony-api/node_modules/node-xmpp-client/lib/Client.js:222:8)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:189:7)
error: Forever detected script exited with code: 1
error: Script restart attempt #9
Starting discovery.
Hub discovered: Great Room at 192.168.0.11.
Updating activities for great-room.
Updating state for great-room.
Updating devices for great-room.
Updating state for great-room.
undefined:1
{"activity":[{"rules":[],"label":"Lower Screen","isTuningDefault":false,"activityTypeDisplayName":"Default","enterActions":[{"name":"SendCommand","parameters":{"Command":"directiondown","DeviceId":"49203209","Modifier":"press"}}],"fixit":{"49203207":{"id":"49203207","isRelativePower":true,"Power":"Off"},"49203209":{"id":"49203209","isAlwaysOn":"true","Power":"On"},"49203208":{"id":"49203208","Power":"Off"},"49920389":{"id":"49920389","isManualPower":true},"49920888":{"id":"49920888","Power":"Off"}},"baseImageUri":"https:\/\/rcbu-test-ssl-amr.s3.amazonaws.com\/","zones":null,"type":"VirtualGeneric","isAVActivity":true,"id":"30232500","controlGroup":[{"name":"NavigationBasic","function":[{"action":"{\"command\":\"DirectionDown\",\"type\":\"IRCommand\",\"deviceId\":\"49203209\"}","name":"DirectionDown","label":"Direction Down"},{"action":"{\"command\":\"DirectionUp\",\"type\":\"IRCommand\",\"deviceId\":\"49203209\"}","name":"DirectionUp","label":"Direction Up"},{"action":"{\"command\":\"OK\",\"type

SyntaxError: Unexpected token ] in JSON at position 73682
    at JSON.parse (<anonymous>)
    at /home/harmony-api/harmony-api/node_modules/harmonyhubjs-client/lib/harmonyclient.js:39:34
    at Array.forEach (native)
    at HarmonyClient.handleStanza (/home/harmony-api/harmony-api/node_modules/harmonyhubjs-client/lib/harmonyclient.js:31:32)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:189:7)
    at Client._handleStanza (/home/harmony-api/harmony-api/node_modules/node-xmpp-client/lib/Client.js:228:12)
    at Client.onStanza (/home/harmony-api/harmony-api/node_modules/node-xmpp-client/lib/Client.js:222:8)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:189:7)
error: Forever detected script exited with code: 1
error: Script restart attempt #10
Starting discovery.
Hub discovered: Great Room at 192.168.0.11."

And on and on it goes....

**Comment by cmon69** [comment]
Ya I hear you, This place only gets you half way there! Unfortunately if you want it done ... You might have to get the rest of the way on your own!

**Comment by stevetb77** [comment]
Oh geez.. I hope not lol.  Otherwise I'll probably never make it all the way.

**Comment by stevetb77** [comment]
I looked at the error more, and realized it appears to be connected to a specific harmony activity.  I didn't need that activity so I erased it.  The error stopped.  All is well.. for now!
