### ISSUE TITLE
Ability to specify HTTP port 

### ISSUE THREAD

**Issue by thebradleysanders** [maddox/harmony-api#87]
I would be a good feature to be able to specify the HTTP API server port to be something other than port 80.

**Comment by maddox** [comment]
It doesn't use port `80`, it uses port `8282` by default, but you can use whatever port you would like.

Per the [README](https://github.com/maddox/harmony-api#running-it):

> Harmony API will run on port 8282 by default. Use the PORT environment variable to use your own port.

Hope this helps!

**Comment by thebradleysanders** [comment]
Awesome thanks for the hard work!
