### ISSUE TITLE
support for mqtt ports and user/password

### ISSUE THREAD

**Issue by luxus** [maddox/harmony-api#9]
hi,
i wondering if its possible to connect to a different server with a specific port and auth with user and password

**Comment by maddox** [comment]
Yeah this is sorely needed. I'll try to get it added soon.

**Comment by luxus** [comment]
i added a second docker with mosquitto without auth for local network and bridge them together, so i can have owntracks and harmony-api :D

**Comment by rpitera** [comment]
Any update on this?  After two weeks of failures and research, I finally got this to run on my Pi and I'd really like to get the rest of it hooked up so I can actually use it, but I use CloudMQTT.  Having this ability would allow that.

**Comment by maddox** [comment]
This has been added with #15.
