### ISSUE TITLE
when ever i run script/bootstrap i receive this

### ISSUE THREAD

**Issue by malhomaid** [maddox/harmony-api#93]
when ever i run script/bootstrap or npm install i receive this.
```
npm ERR! git clone git@github.com:github:maddox/harmonyhubjs-client Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-github-maddox-harmonyhubjs-client-def8ff3d'...
npm ERR! git clone git@github.com:github:maddox/harmonyhubjs-client Permission denied (publickey).
npm ERR! git clone git@github.com:github:maddox/harmonyhubjs-client fatal: Could not read from remote repository.
npm ERR! git clone git@github.com:github:maddox/harmonyhubjs-client
npm ERR! git clone git@github.com:github:maddox/harmonyhubjs-client Please make sure you have the correct access rights
npm ERR! git clone git@github.com:github:maddox/harmonyhubjs-client and the repository exists.
npm ERR! notarget No compatible version found: harmonyhubjs-client@'github:maddox/harmonyhubjs-client#for-harmony-api'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["1.1.2","1.1.3","1.1.4","1.1.5","1.1.6","1.1.7","1.1.8","1.1.9","1.1.10"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! System Linux 4.9.80-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/Downloads/Harmony/harmony-api
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! code ETARGET
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Downloads/Harmony/harmony-api/npm-debug.log
npm ERR! not ok code 0

```

**Comment by mbijker** [comment]
I'm getting exactly the same :(
Hoping to find a solution...

**Comment by jiggahertz86** [comment]
same error here, any suggestions?

**Comment by maddox** [comment]
What is this path?

> /root/.npm/_git-remotes/git-github-com-github-maddox-harmonyhubjs-client-def8ff3d

What environment are you all running this on? This is super weird.

**Comment by maddox** [comment]
Oh i suppose it's doing a git clone when npm installing directly from github. It's using SSH to clone down the package. It's a public repo, so I'm not sure why it's complaining. 

1. If you set up git on your device with github support (add your ssh key to your github account) it should work. 
2. If you ssh into your device with `ssh -A host`, it will forward and use the key on your local device and probably work.
3. I should probably somehow ensure this uses `https` and not `ssh` for the package
4. I'm pretty sure what ever changes I had in my fork, were merged into the original package, I should just move back to it.

**Comment by maddox** [comment]
I just opened #94.

Could someone switch to this branch: `back-to-regular-harmonyhubjs-client` and try `script/bootstrap`

Try to `rm -Rf node_modules` first.

**Comment by mbijker** [comment]
That branch did the trick for me!
I'm getting a few warnings but it works again!
Thanks! Very happy with it!

The warnings I'm getting:

pi@raspberrypi:~/harmony-api $ script/bootstrap
npm WARN engine harmonyhubjs-client@1.1.10: wanted: {"npm":">=3.0.0"} (current: {"node":"4.8.2","npm":"1.4.21"})
npm WARN deprecated node-xmpp-stanza@1.1.0: use @xmpp/xml package <https://www.npmjs.com/package/@xmpp/xml>
npm WARN deprecated node-xmpp-jid@2.3.0: use @xmpp/jid package <https://www.npmjs.com/package/@xmpp/jid>
parameterize@0.0.7 node_modules/parameterize

**Comment by maddox** [comment]
Great! I’ll merge the pr. Those other messages are benign.
